name: Push ROCm Image to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  push-image:
    runs-on: self-hosted
    steps:
      - name: Log in to GitHub Container Registry (GHCR)
        shell: pwsh
        run: |
          "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push pre-built image to GHCR
        shell: pwsh
        run: |
          docker push ghcr.io/moyu-dev16/amd-mc3-rag:v1
          docker push ghcr.io/moyu-dev16/amd-mc3-rag:latest
